# Generated by Django 5.1.1 on 2024-10-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wrapped',
        ),
    ]
