# Generated by Django 5.1.1 on 2024-10-31 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wrapped', '0002_delete_wrapped'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteWrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.JSONField()),
                ('top_artists', models.JSONField()),
                ('artist_songs', models.JSONField(default=dict)),
                ('top_tracks', models.JSONField()),
                ('top_genres', models.JSONField(default=list)),
                ('genre_songs', models.JSONField(default=dict)),
                ('average_valence', models.FloatField()),
                ('time_range', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
