# Generated by Django 5.1.1 on 2024-10-31 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteWrap',
            new_name='SaveWrap',
        ),
    ]
