# Generated by Django 5.1.1 on 2024-11-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0005_saveduowrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveduowrap',
            name='user1_data',
        ),
        migrations.RemoveField(
            model_name='saveduowrap',
            name='user2_data',
        ),
    ]
