# Generated by Django 5.1.1 on 2024-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0006_remove_saveduowrap_user1_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveduowrap',
            name='user1_first_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveduowrap',
            name='user1_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/user1/'),
        ),
        migrations.AddField(
            model_name='saveduowrap',
            name='user2_first_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveduowrap',
            name='user2_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/user2/'),
        ),
    ]
