# Generated by Django 5.1.1 on 2024-11-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0007_saveduowrap_user1_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveduowrap',
            name='user1_first_name',
        ),
        migrations.RemoveField(
            model_name='saveduowrap',
            name='user1_profile_pic',
        ),
        migrations.RemoveField(
            model_name='saveduowrap',
            name='user2_first_name',
        ),
        migrations.RemoveField(
            model_name='saveduowrap',
            name='user2_profile_pic',
        ),
        migrations.AddField(
            model_name='saveduowrap',
            name='user1_data',
            field=models.JSONField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveduowrap',
            name='user2_data',
            field=models.JSONField(default='Unknown'),
            preserve_default=False,
        ),
    ]
