# Generated by Django 5.1.1 on 2024-12-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0008_remove_saveduowrap_user1_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveduowrap',
            name='compatibility',
            field=models.IntegerField(),
        ),
    ]
